site_name: PromptSite
site_description: A tool to manage prompts with version control
repo_url: https://github.com/dkuang1980/promptsite
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Configuration: user-guide/configuration.md
    - CLI Usage: user-guide/cli.md
    - Python API: user-guide/python-api.md
    - Decorator Usage: user-guide/decorator.md
    - Variable Definitions: user-guide/variable-definitions.md
    - Synthetic Datasets: user-guide/dataset.md
  - API Reference:
    - Core: api/core.md
    - Storage: api/storage.md
    - Models: api/models.md
    - Exceptions: api/exceptions.md
    - Query: api/query.md
    - LLM: api/llm.md
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search  
  - mkdocstrings