name: Test and Lint
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest -cov=promptsite --cov-report=html --cov-fail-under=75 -s tests/ 

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Format with black
        run: |
          poetry run black promptsite tests 
      - name: Ruff format and check
        run: |
          poetry run ruff format promptsite tests 
          poetry run ruff check promptsite tests